apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: python-demo

  template:

    metadata:
      labels:
        app: python-demo

    spec:

      containers:

      - name: python-demo

        image: IMAGE_NAME

        ports:

        - containerPort: 5000
